### ISSUE TITLE
Css spacing issue on main page

### ISSUE THREAD

**Issue by dovid11564** [dovid11564/magic-seaweed-clone#25]
![image](https://github.com/dovid11564/magic-seaweed-clone/assets/110751525/8e4efbd9-7dbd-431a-a9c9-7486b67d9f91)

Having trouble refactoring the css to make it take up the entire page!

**Comment by web-dev-kushal** [comment]
I want to work omn this issue...Please do assign me

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by dovid11564** [comment]
Solved by #26
